### ISSUE TITLE
Make more spectator controls customizable

### ISSUE THREAD

**Issue by utf-4096** [utf-4096/butterspades#10]
Controls like V and middle mouse button are not currently customizable.
Reported by @X-DE1

**Comment by utf-4096** [comment]
@x-de1 I don't think I'm getting the issue here, since sneak (V) can be changed already. I'm not sure what you mean with the mouse wheel, either.

**Comment by X-DE1** [comment]
when you die you can spectate your team with the right click, the left click, the mouse wheel button and with the V you can change between first person and third person.
I don't want to change the sneak button, I want to change the button that changes between first person and third person with the space for example.
With the mouse wheel button you can switch between the living players, not like using right click or left click where you can see dead players waiting to respawn
