### ISSUE TITLE
Chat Log and Change Spectator Mode Controls

### ISSUE THREAD

**Issue by X-DE1** [utf-4096/butterspades#9]
It would be great if you add chat log to copy text and the option to change spectator mode controls the V and mouse wheel button.
It would also be great if you put a width limit on the chat box since then people write very long texts that cover the whole screen and you can't read the whole message.
![1673584405](https://user-images.githubusercontent.com/101435795/212238356-90e1adb3-dc3b-403f-bfb9-ea4fb6bb247b.png)

**Comment by utf-4096** [comment]
hey, again, please create *separate* issues for each bug or feature you request, as it makes tracking and searching easier.

**Comment by utf-4096** [comment]
I've created the issues for these: #10 #11 #12. thanks for the report!
